---
   # "Apache Installation using docker"  

    - name: Copy website file template
      template:
        src: index.html.j2
        dest: "/home/{{ system_user }}/index.html"

    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80" 
        volumes: 
          - "/home/{{ system_user }}/index.html:/usr/local/apache2/htdocs/index.html"
